version: '3.8'

services:
  claude-sandbox:
    build: .
    container_name: claude-sandbox
    volumes:
      # Mount the entire git repository to preserve git history and enable commits
      - .:/workspace
      # Mount git config from host (optional, for consistent git identity)
      - ~/.gitconfig:/home/claude/.gitconfig:ro
      # Mount SSH keys if needed for git operations
      - ~/.ssh:/home/claude/.ssh:ro
    working_dir: /workspace
    environment:
      # Preserve git author information
      - GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME:-$(git config user.name)}
      - GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL:-$(git config user.email)}
      - GIT_COMMITTER_NAME=${GIT_COMMITTER_NAME:-$(git config user.name)}
      - GIT_COMMITTER_EMAIL=${GIT_COMMITTER_EMAIL:-$(git config user.email)}
    stdin_open: true
    tty: true
    # Security settings
    security_opt:
      - no-new-privileges:true
    read_only: false  # Need write access for git operations
    tmpfs:
      - /tmp:noexec,nosuid,nodev,size=100m
      - /var/tmp:noexec,nosuid,nodev,size=50m
    cap_drop:
      - ALL
    cap_add:
      - DAC_OVERRIDE  # Needed for file operations
    # Resource limits
    mem_limit: 1g
    memswap_limit: 1g
    cpu_quota: 100000  # 1 CPU core
    pids_limit: 100
    # Network isolation
    network_mode: none  # No network access by default